version: '3.9'
services: 
  db:
    container_name: mysql_users_challenge
    image: mysql:8-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=users
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
